import { ThemeConfig } from '../types'

const defaultTheme: ThemeConfig = {
  root: {
    colors: {
      brand: '#FF0000',
      'accent-1': '',
      'accent-2': '',
      'accent-3': '',
      'accent-4': '',
      'neutral-1': '',
      'neutral-2': '',
      'neutral-3': '',
      'neutral-4': '',
      error: '',
      warning: '',
      success: '',
      unknown: '',
      disabled: '',
      'light-1': '#F8F8F8',
      'light-2': '#F2F2F2',
      'light-3': '#EDEDED',
      'light-4': '#DADADA',
      'light-5': '#DADADA',
      'light-6': '#DADADA',
      'dark-1': '#333333',
      'dark-2': '#555555',
      'dark-3': '#777777',
      'dark-4': '#999999',
      'dark-5': '#999999',
      'dark-6': '#999999',
      transparent: 'transparent',
    },
    spacing: {
      xxsmall: '3px',
      xsmall: '5px',
      small: '10px',
      medium: '20px',
      large: '40px',
      xlarge: '60px',
      xxlarge: '80px',
      unset: '',
    },
    borderSizes: {
      xxsmall: '1px',
      xsmall: '2px',
      small: '3px',
      medium: '5px',
      large: '10px',
      xlarge: '20px',
      xxlarge: '40px',
      unset: '',
    },
    sizes: {
      xxsmall: '40px',
      xsmall: '80px',
      small: '160px',
      medium: '320px',
      large: '640px',
      xlarge: '960px',
      xxlarge: '1280px',
      full: '100%',
      unset: '',
    },
  },
  paragraph: {
    sizes: {
      xxsmall: '11px',
      xsmall: '12px',
      small: '14px',
      medium: '16px',
      large: '18px',
      xlarge: '20px',
      xxlarge: '24px',
    },
  },
  heading: {
    sizes: {
      xxsmall: '3px',
      xsmall: '5px',
      small: '10px',
      medium: '20px',
      large: '40px',
      xlarge: '60px',
      xxlarge: '80px',
      unset: '',
    },
  },
}

export default defaultTheme
